In [3]:
import pandas as pd
import xarray as xr
import numpy as np
import os
import re
import subprocess
from pathlib import Path
import boto3
from botocore.client import Config
from botocore import UNSIGNED
from botocore.config import Config as BotocoreConfig
import fsspec
import s3fs
from io import StringIO

In [ ]:
# Create an S3 client with anonymous access
'''
s3 = boto3.client(
    's3',
    endpoint_url = 'https://sdsc.osn.xsede.org',
    config = Config(
        signature_version = UNSIGNED,
        s3 = {'addressing_style': 'path'}
    )
)
'''

In [4]:
fs = fsspec.filesystem(
    "s3",
    anon = True,
    client_kwargs = {"endpoint_url": "https://sdsc.osn.xsede.org"}
    )

bucket_name = "agr230002-bucket01"
csv_prefix = "hake_data/label_allocations/2017/transect_subgroup_class_dataframes/"
zarr_prefix = "hake_data/data_zarr/MVBS"

In [5]:
# Load region labels from CSV files in S3

def load_region_labels_s3(prefix, bucket = bucket_name):
    # List CSV objects
    all_regions = []
    full_prefix = f"{bucket}/{prefix}"
    
    all_keys = fs.find(full_prefix)
    csv_keys = [k for k in all_keys if k.endswith(".csv")]
    print(f"Found {len(csv_keys)} CSV files in: {full_prefix}")

    for path in csv_keys:
        with fs.open(path, mode="r") as f:
            df = pd.read_csv(f)

            if not df.empty:
                file_name = path.split("/")[-1]
                df["source_file"] = file_name.replace("--all_class_info.csv", "")
                all_regions.append(df)

    if not all_regions:
        return pd.DataFrame()

    combined_df = pd.concat(all_regions, ignore_index=True)

    if "time" not in combined_df.columns:
        return pd.DataFrame()

    results = []
    for _, row in combined_df.iterrows():
        time_list = re.findall(r"'([^']+)'", row["time"])
        if time_list:
            time = pd.to_datetime(time_list)
            time_ms = time.astype("int64") / 10**6
            results.append({
                "id": row["source_file"],
                "start_time": time.min(),
                "end_time": time.max(),
                "start_time_ms": time_ms.min(),
                "end_time_ms": time_ms.max()
            })

    return pd.DataFrame(results).sort_values(by="start_time").reset_index(drop=True)

region_time_df = load_region_labels_s3(prefix = csv_prefix)
region_time_df

Found 176 CSV files in: agr230002-bucket01/hake_data/label_allocations/2017/transect_subgroup_class_dataframes/

,id,start_time,end_time,start_time_ms,end_time_ms
0,x0003_0_wt_20170626_125619_f0013,2017-06-26 13:01:22.781000,2017-06-26 13:27:43.071000,1.498482e+12,1.498484e+12
1,x0003_0_wt_20170626_125619_f0013,2017-06-26 13:58:29.580000,2017-06-26 14:24:16.405000,1.498486e+12,1.498487e+12
2,x0004_0_wt_20170626_191344_f0006,2017-06-26 20:21:13.749000,2017-06-26 20:42:11.118500,1.498508e+12,1.498510e+12
3,x0004_0_wt_20170626_191344_f0006,2017-06-26 20:42:11.118500,2017-06-26 21:23:28.006500,1.498510e+12,1.498512e+12
4,x0004_2_wt_20170627_004507_f0007,2017-06-27 00:28:51.374500,2017-06-27 00:45:13.311000,1.498523e+12,1.498524e+12
...,...,...,...,...,...
266,x0131_0_wt_20170904_141338_f0004,2017-09-04 15:02:31.003500,2017-09-04 15:02:45.599000,1.504537e+12,1.504537e+12
267,x0131_0_wt_20170904_141338_f0004,2017-09-04 15:04:50.926000,2017-09-04 15:05:05.567000,1.504537e+12,1.504538e+12
268,x0131_0_wt_20170904_141338_f0004,2017-09-04 15:05:36.848500,2017-09-04 15:05:49.235000,1.504538e+12,1.504538e+12
269,x0131_2_wt_20170904_172930_f0010,2017-09-04 17:51:59.891000,2017-09-04 18:40:14.303000,1.504548e+12,1.504550e+12
270,x0127_0_wt_20170906_194741_f0003,2017-09-06 20:04:05.978500,2017-09-06 20:06:08.192000,1.504728e+12,1.504728e+12

In [ ]:
# Local version of the function

'''
def load_region_labels(csv_dir):
    all_regions = []
    
    # Read all CSV files at once
    for file in os.listdir(csv_dir):
        if file.endswith('.csv'):
            path = os.path.join(csv_dir, file)
            df = pd.read_csv(path)
            if not df.empty:
                df['source_file'] = file.replace('--all_class_info.csv', '')
                all_regions.append(df)
    
    # If no CSV files were found, return an empty DataFrame
    if not all_regions:
        return pd.DataFrame()
    
    # Concatenate all DataFrames into one
    combined_df = pd.concat(all_regions, ignore_index=True)
    
    if 'time' not in combined_df.columns:
        return pd.DataFrame()
    
    # Extract time information from the 'time' column
    results = []
    for _, row in combined_df.iterrows():
        time_list = re.findall(r"'([^']+)'", row['time'])
        if time_list:
            time = pd.to_datetime(time_list)
            time_ms = time.astype('int64') / 10**6
            results.append({
                'id': row['source_file'],
                'start_time': time.min(),
                'end_time': time.max(),
                'start_time_ms': time_ms.min(),
                'end_time_ms': time_ms.max()
            })
    
    return pd.DataFrame(results).sort_values(by=['start_time']).reset_index(drop=True)


csv_dir = 'region_csv'
region_time_df_local = load_region_labels(csv_dir)
region_time_df_local
'''

,id,start_time,end_time,start_time_ms,end_time_ms
0,x0003_0_wt_20170626_125619_f0013,2017-06-26 13:01:22.781000,2017-06-26 13:27:43.071000,1.498482e+12,1.498484e+12
1,x0003_0_wt_20170626_125619_f0013,2017-06-26 13:58:29.580000,2017-06-26 14:24:16.405000,1.498486e+12,1.498487e+12
2,x0004_0_wt_20170626_191344_f0006,2017-06-26 20:21:13.749000,2017-06-26 20:42:11.118500,1.498508e+12,1.498510e+12
3,x0004_0_wt_20170626_191344_f0006,2017-06-26 20:42:11.118500,2017-06-26 21:23:28.006500,1.498510e+12,1.498512e+12
4,x0004_2_wt_20170627_004507_f0007,2017-06-27 00:28:51.374500,2017-06-27 00:45:13.311000,1.498523e+12,1.498524e+12
...,...,...,...,...,...
266,x0131_0_wt_20170904_141338_f0004,2017-09-04 15:02:31.003500,2017-09-04 15:02:45.599000,1.504537e+12,1.504537e+12
267,x0131_0_wt_20170904_141338_f0004,2017-09-04 15:04:50.926000,2017-09-04 15:05:05.567000,1.504537e+12,1.504538e+12
268,x0131_0_wt_20170904_141338_f0004,2017-09-04 15:05:36.848500,2017-09-04 15:05:49.235000,1.504538e+12,1.504538e+12
269,x0131_2_wt_20170904_172930_f0010,2017-09-04 17:51:59.891000,2017-09-04 18:40:14.303000,1.504548e+12,1.504550e+12
270,x0127_0_wt_20170906_194741_f0003,2017-09-06 20:04:05.978500,2017-09-06 20:06:08.192000,1.504728e+12,1.504728e+12

In [ ]:
# Load all MVBS zarr files from S3 and extract ping_time range

def load_mvbs_zarr_s3(base_prefix, years, bucket = bucket_name, max_seconds = 1e8): # How to determine 'max_seconds'?
    ping_records = []

    # Loop over each Zarr within that year
    for year in years:
        prefix = f"{base_prefix}/{year}/"
        print(f"Processing year: {year}")

        try:
            all_keys = fs.ls(f"{bucket}/{prefix}", detail=False)
        except Exception as e:
            print(f"Failed to list {prefix}: {e}")
            continue
        
        # List all .zarr folders under the prefix
        zarr_paths = [key for key in all_keys if key.endswith(".zarr")]
        print(f"Found {len(zarr_paths)} zarr in: {prefix}")

        # Open each .zarr and extract ping_time range
        for zarr_key in sorted(zarr_paths):
            try:
                ds = xr.open_zarr(fs.get_mapper(f"s3://{zarr_key}"))
                arr = ds['ping_time'].values

                if np.issubdtype(arr.dtype, np.datetime64):
                    times = pd.to_datetime(arr)
                else:
                    raise ValueError("Not datetime64")

            # Fallback: raw offsets (seconds) + manual conversion
            except ValueError:
                ds = xr.open_zarr(fs.get_mapper(f"s3://{zarr_key}"), decode_times=False)
                raw = ds['ping_time'].values

                # filter out extreme values
                clean = raw[(raw >= 0) & (raw <= max_seconds)]
                if clean.size == 0:
                    print(f"Skipping {zarr_key}: no valid ping times")
                    continue
                    
                print(len(raw) - len(clean), "invalid ping times in:", zarr_key)

                # parse “<unit> since <ref>”
                units = ds["ping_time"].attrs.get("units", "")
                m = re.search(r"(\w+)\s+since\s+(.+)", units)
                if not m:
                    print(f"Skipping {zarr_key}: malformed units “{units}”")
                    continue
                
                # map to pandas timedelta unit
                unit_str, ref_str = m.groups()
                ref = pd.to_datetime(ref_str)
                td_unit = {"seconds": "s", "second": "s", "minutes": "m", "hours": "h", "days": "D"}.get(unit_str.lower(), "s")
                times = ref + pd.to_timedelta(clean, unit=td_unit)
            

            start_ts = times.min()
            end_ts = times.max()

            ping_records.append({
                'id': zarr_key.split('/')[-1].replace(".zarr", ""),
                'ping_start': start_ts,
                'ping_end': end_ts,
                'ping_start_ms': start_ts.value / 1e6,
                'ping_end_ms': end_ts.value / 1e6
            })

    return pd.DataFrame(ping_records).sort_values(by="ping_start").reset_index(drop=True)


years = [2017] # Determined by the region label csv files
ping_time_df = load_mvbs_zarr_s3(zarr_prefix, years)
ping_time_df

Processing year: 2017
Found 104 zarr in: hake_data/data_zarr/MVBS/2017/
174 invalid ping times in: agr230002-bucket01/hake_data/data_zarr/MVBS/2017/x0062_0_wt_20170731_031153_f0003.zarr
2 invalid ping times in: agr230002-bucket01/hake_data/data_zarr/MVBS/2017/x0062_10_wt_20170731_194315_f0003.zarr
732 invalid ping times in: agr230002-bucket01/hake_data/data_zarr/MVBS/2017/x0062_2_wt_20170731_130448_f0004.zarr
312 invalid ping times in: agr230002-bucket01/hake_data/data_zarr/MVBS/2017/x0062_4_wt_20170731_145057_f0004.zarr
299 invalid ping times in: agr230002-bucket01/hake_data/data_zarr/MVBS/2017/x0062_6_wt_20170731_164016_f0003.zarr
15 invalid ping times in: agr230002-bucket01/hake_data/data_zarr/MVBS/2017/x0062_8_wt_20170731_180848_f0002.zarr
1138 invalid ping times in: agr230002-bucket01/hake_data/data_zarr/MVBS/2017/x0063_0_wt_20170731_230214_f0014.zarr

,id,ping_start,ping_end,ping_start_ms,ping_end_ms
0,x0001_0_wt_20170625_165809_f0003,2017-06-25 16:58:10,2017-06-25 17:57:05,1.498410e+12,1.498413e+12
1,x0001_2_wt_20170625_191315_f0003,2017-06-25 19:13:15,2017-06-25 20:11:45,1.498418e+12,1.498422e+12
2,x0001_4_wt_20170625_212354_f0002,2017-06-25 21:23:55,2017-06-25 21:47:55,1.498426e+12,1.498427e+12
3,x0001_6_wt_20170625_225249_f0002,2017-06-25 22:52:50,2017-06-25 23:02:40,1.498431e+12,1.498432e+12
4,x0001_8_wt_20170626_001831_f0003,2017-06-26 00:18:30,2017-06-26 01:10:55,1.498436e+12,1.498439e+12
...,...,...,...,...,...
99,x0062_4_wt_20170731_145057_f0004,2017-07-31 14:50:55,2017-10-25 16:11:07,1.501513e+12,1.508948e+12
100,x0062_6_wt_20170731_164016_f0003,2017-07-31 16:40:15,2017-07-31 17:33:51,1.501519e+12,1.501522e+12
101,x0062_8_wt_20170731_180848_f0002,2017-07-31 18:08:45,2017-07-31 19:17:01,1.501525e+12,1.501529e+12
102,x0062_10_wt_20170731_194315_f0003,2017-07-31 19:43:15,2017-07-31 20:51:31,1.501530e+12,1.501534e+12
103,x0063_0_wt_20170731_230214_f0014,2017-07-31 23:02:15,2017-08-01 03:28:41,1.501542e+12,1.501558e+12

In [ ]:
# Local version of the function

'''
def load_mvbs_zarr(mvbs_dir, max_seconds = 1e8): # How to determine 'max_seconds'?
    ping_records = []

    # Loop over each Zarr within that year
    for zarr_path in mvbs_dir.glob("*.zarr"):
        #print(f"Loading {zarr_path}")        
        try:
            ds = xr.open_zarr(str(zarr_path))
            arr = ds['ping_time'].values
            
            if np.issubdtype(arr.dtype, np.datetime64):
                times = pd.to_datetime(arr)
            else:
                raise ValueError("Not datetime64")
        
        # Fallback: raw offsets (seconds) + manual conversion
        except ValueError:
            ds = xr.open_zarr(str(zarr_path), decode_times=False)
            raw = ds['ping_time'].values
                
            # filter out extreme values
            clean = raw[(raw >= 0) & (raw <= max_seconds)]
            if clean.size == 0:
                print(f"Skipping {zarr_path.name}: no valid ping times")
                continue

            # parse “<unit> since <ref>”
            units = ds["ping_time"].attrs.get("units", "")
            m = re.search(r"(\w+)\s+since\s+(.+)", units)
            if not m:
                print(f"Skipping {zarr_path.name}: malformed units “{units}”")
                continue
            
            unit_str, ref_str = m.groups()
            ref = pd.to_datetime(ref_str)

            # map to pandas timedelta unit
            unit_map = {
                "seconds": "s", "second": "s",
                "minutes": "m", "hours": "h", "days": "D"
            }
            td_unit = unit_map.get(unit_str.lower(), "s")
            times = ref + pd.to_timedelta(clean, unit = td_unit)

        start_ts = times.min()
        end_ts = times.max()
        
        ping_records.append({
            'id': zarr_path.stem,                       
            'ping_start': start_ts,  
            'ping_end': end_ts, 
            'ping_start_ms': start_ts.value / 1e6, 
            'ping_end_ms': end_ts.value / 1e6
        })

    ping_time_df = pd.DataFrame(ping_records).sort_values(by="ping_start").reset_index(drop=True)
        
    return ping_time_df


mvbs_dir = Path('mvbs_sample/2017')
ping_time_df_local = load_mvbs_zarr(mvbs_dir)
ping_time_df_local
'''

,id,ping_start,ping_end,ping_start_ms,ping_end_ms
0,x0001_0_wt_20170625_165809_f0003,2017-06-25 16:58:10,2017-06-25 17:57:05,1.498410e+12,1.498413e+12
1,x0001_2_wt_20170625_191315_f0003,2017-06-25 19:13:15,2017-06-25 20:11:45,1.498418e+12,1.498422e+12
2,x0001_4_wt_20170625_212354_f0002,2017-06-25 21:23:55,2017-06-25 21:47:55,1.498426e+12,1.498427e+12
3,x0001_6_wt_20170625_225249_f0002,2017-06-25 22:52:50,2017-06-25 23:02:40,1.498431e+12,1.498432e+12
4,x0001_8_wt_20170626_001831_f0003,2017-06-26 00:18:30,2017-06-26 01:10:55,1.498436e+12,1.498439e+12
...,...,...,...,...,...
99,x0062_4_wt_20170731_145057_f0004,2017-07-31 14:50:55,2017-07-31 17:07:27,1.501513e+12,1.501521e+12
100,x0062_6_wt_20170731_164016_f0003,2017-07-31 16:40:15,2017-07-31 17:16:47,1.501519e+12,1.501521e+12
101,x0062_8_wt_20170731_180848_f0002,2017-07-31 18:08:45,2017-08-01 12:53:13,1.501525e+12,1.501592e+12
102,x0062_10_wt_20170731_194315_f0003,2017-07-31 19:43:15,2017-07-31 20:23:15,1.501530e+12,1.501533e+12
103,x0063_0_wt_20170731_230214_f0014,2017-07-31 23:02:15,2017-08-01 01:50:00,1.501542e+12,1.501552e+12

### TODO: Optimize Matching
Check which year exists in region labels first and only load those specific years of zarr to match

1. Create region_time_df
2. Check which year is present in region_time_df
3. Load those specific years of zarr data, create ping_time_df_year (or merge into 1 ping_time_df)
4. Find match

In [ ]:
# Using milliseconds for more precise matching
def find_matching_zarrs(row):
    mask = (
        (row['start_time_ms'] <= ping_time_df['ping_end_ms']) &
        (row['end_time_ms'] >= ping_time_df['ping_start_ms'])
    )
    return ping_time_df.loc[mask, 'id'].tolist()

# Apply it to get a list of Zarr paths per region
region_time_df['matching_zarrs'] = region_time_df.apply(find_matching_zarrs, axis=1)

region_time_df

In [ ]:
# Check matching zarrs
def check_matches_simple(region_time_df, ping_time_df):
    # Show example for first 5 regions
    for i in range(min(5, len(region_time_df))):
        region = region_time_df.iloc[i]
        print(f"\nRegion: {region['id']}")
        print(f"Region time: {region['start_time']} to {region['end_time']}")
        print(f"Matches: {region['matching_zarrs']}")
        
        # Show times for matched MVBS files
        for mvbs_id in region['matching_zarrs']:
            mvbs = ping_time_df[ping_time_df['id'] == mvbs_id].iloc[0]
            print(f"  - {mvbs_id}: {mvbs['ping_start']} to {mvbs['ping_end']}")
        print("-" * 50)

# Check if any regions have no matches
no_matches = region_time_df[region_time_df['matching_zarrs'].apply(len) == 0]
print(f"Regions with no matches: {len(no_matches)} out of {len(region_time_df)}")

# Basic statistics
match_counts = region_time_df['matching_zarrs'].apply(len)
print(f"Average matches per region: {match_counts.mean():.2f}")
print(f"Max matches for a region: {match_counts.max()}")

# Run the check
check_matches_simple(region_time_df, ping_time_df)

# Issues

When loading the data directly from s3, ```ds['ping_time'].values``` are different from data reading from local

### Abnormal
Example file: ```2017/x0062_8_wt_20170731_180848_f0002.zarr```

Load directly from s3

In [9]:
# Test loading a zarr file
bucket = "agr230002-bucket01"
zarr_key = "hake_data/data_zarr/MVBS/2017/x0062_8_wt_20170731_180848_f0002.zarr"
full_path = f"s3://{bucket}/{zarr_key}"

s3_ds = xr.open_zarr(fs.get_mapper(full_path), decode_times=False)
s3_ds

<xarray.Dataset> Size: 6MB
Dimensions:            (channel: 3, ping_time: 344, depth: 759)
Coordinates:
  * channel            (channel) <U37 444B '' '' ''
  * depth              (depth) float64 6kB nan nan nan nan ... nan nan nan nan
  * ping_time          (ping_time) int64 3kB 0 4714471308 ... 4616075712
Data variables:
    Sv                 (channel, ping_time, depth) float64 6MB dask.array<chunksize=(3, 344, 759), meta=np.ndarray>
    frequency_nominal  (channel) float64 24B dask.array<chunksize=(3,), meta=np.ndarray>
    latitude           (ping_time) float64 3kB dask.array<chunksize=(344,), meta=np.ndarray>
    longitude          (ping_time) float64 3kB dask.array<chunksize=(344,), meta=np.ndarray>
Attributes:
    processing_function:          commongrid.compute_MVBS
    processing_level:             Level 3A
    processing_level_url:         https://echopype.readthedocs.io/en/stable/p...
    processing_software_name:     echopype
    processing_software_version:  0.9.0
    processing_time:              2024-08-14T00:14:32Z

In [10]:
s3_ds['ping_time'].values

array([                  0,          4714471308,                   0,
                4714471308, 7939626486501289804, 7305790156125334881,
                         0,                  35,                  40,
                        45,                  50,                  55,
                        60,                  65,                  70,
                        75,                  80,                  85,
                        90,                  95,                 100,
                       105,                 110,                 115,
                       120,                 125,                 130,
                       135,                 140,                 145,
                       150,                 155,                 160,
                       165,                 170,                 175,
                       180,                 185,                 190,
                       195,                 200,                 205,
                       210,                 215,                 220,
                       225,                 230,                 235,
                       240,                 245,                 250,
                       255,                 260,                 265,
                       270,                 275,                 280,
                       285,                 290,                 295,
                       300,                 305,                 310,
                       315,          4696422896,          4696421264,
                4358586032,          4301921320,          4696417088,
                4623984560,          4301921512,          4696961360,
                4616107504,          4301922328,          4616107504,
                4623984560,          4616107504,          4616107504,
                4623984560,          4616107504,          4616107504,
                4616107504,          4696960400,          4696675440,
                4301921368,          4697078544,          4616107504,
                4623984560,          4616107504,          4616107504,
                4616107504,          4616107504,          4623984560,
                4616107504,          4616107504,          4616107504,
                4616107504,          4301922184,          4697017920,
                4301919360,          4625799168,          4616101360,
                4301922328,          4616101360,          4616101360,
                4301923768,          4301923864,          4301919360,
                4626446640,          4626448224,          4623974448,
                4626446880,          4623974448,          4626435744,
                4623984560,          4301921608,          4626434112,
                4305409200,          4301921320,          4626446832,
                4301921368,          4612683440,          4301922184,
                4623984560,          4301919360,          4301919360,
                4626441600,          4301922184,          4301919360,
                4301919360,          4626437856,          4333072944,
                4301922328,          4333072944,          4333072944,
                4626436272,          4355999792,          4301921608,
                4626433056,          4591025456,          4301921320,
                4626436128,          4301471312,          4301921320,
                4301471312,          4626441168,          4623974448,
                4301921368,          4623974448,          4623974448,
                4623974448,          4301921368,          4301471312,
                4301471312,          4301919360,          4355999792,
                4355999792,          4355999792,          4591025456,
                4301471312,          4355999792,          4626435312,
                4342356144,          4301922328,          4342356144,
                4342356144,          4626433632,          4333072944,
                4301923768,          4626438672,          4301923864,
                4627579696,          4301921608,          4626434256,
                4301951352,          4301919360,          4333072944,
                4301951352,          4333072944,          4301951352,
                4333072944,          4626433728,          4626445824,
                4333291824,          4301921608,          4333291824,
                4626433344,          4333926128,          4301921320,
                4626445440,          4342356144,          4301921608,
                4342356144,          4626443664,          4333291504,
                4301921512,          4342356144,          4342356144,
                4626440736,          4333291824,          4301921608,
                4333291824,          4626440208,          4357334832,
                4301921368,          4333291824,          4301922184,
                4333291824,          4301919360,          4301919360,
                4626433584,          4304144496,          4301922328,
                4304144496,          4304144496,          4626441504,
                4308059056,          4301921608,          4626437232,
                4357359088,          4301921320,          4626433296,
                4342356144,          4301921368,          4342356144,
                4342356144,          4342356144,          4301919360,
                4308059056,          4308059056,          4308059056,
                4357359088,          4342356144,          4308059056,
                4301919360,          4626436848,          4333291824,
                4301922184,          4301919360,          4301919360,
                4626438960,          4626436944,          4301471432,
                4301921320,          4627593968,          4301921368,
                4627593904,          4301919360,          4301471432,
                4301919360,          4301919360,          4626434832,
                4626438576,          4301471432,          4301922184,
                4301471432,          4301919360,          4301919360,
                4626440016,          4333072944,          4301922328,
                4333072944,          4333072944,          4626433536,
                4355999792,          4301921608,          4626435072,
                4591025456,          4301921320,          4626435936,
                4301471312,          4301921320,          4301471312,
                4626434400,          4623974448,          4301921368,
                4623974448,          4623974448,          4623974448,
                4301921512,          4301471312,          4301471312,
                4626438768,          4591122992,          4301922328,
                4591122992,          4591122992,          4591122992,
                4626448128,          4301921368,          4591122992,
                4301919360,          4355999792,          4355999792,
                4355999792,          4591025456,          4301471312,
                4355999792,          4626446736,          4303710896,
                4301922328,          4303710896,          4303710896,
                4626444192,          4333072944,          4301923768,
                4626436032,          4301923864,          4625445040,
                4301921608,          4626437376,          4301951352,
                4301919360,          4333072944,          4301951352,
                4333072944,          4301951352,          4333072944,
                4626432720,          4317506928,          4301922328,
                4317506928,          4317506928,          4626444336,
                4303710896,          4301923768,          4301921320,
                4626447264,          4303710896,          4616074608,
                4303710896,          4303710896,          4301921704,
                4301911136,          4301921368,          4301911136,
                4303710896,          4301921224,          4303710896,
                4303710896,          4301921320,          4616064720,
                4303710896,          4616075712])

In [11]:
s3_ds['ping_time'].attrs

{'axis': 'T',
 'calendar': 'proleptic_gregorian',
 'long_name': 'Ping time',
 'standard_name': 'time',
 'units': 'seconds since 2017-07-31 18:08:45'}

Copied from s3 to local (have weird ping_time values)

In [12]:
ds = xr.open_zarr('mvbs_sample/2017/x0062_8_wt_20170731_180848_f0002.zarr', decode_times=False)
ds

<xarray.Dataset> Size: 6MB
Dimensions:            (channel: 3, ping_time: 344, depth: 759)
Coordinates:
  * channel            (channel) <U37 444B '' '' ''
  * depth              (depth) float64 6kB nan nan nan nan ... nan nan nan nan
  * ping_time          (ping_time) int64 3kB 0 3782820132520198796 ... 0 0
Data variables:
    Sv                 (channel, ping_time, depth) float64 6MB dask.array<chunksize=(3, 344, 759), meta=np.ndarray>
    frequency_nominal  (channel) float64 24B dask.array<chunksize=(3,), meta=np.ndarray>
    latitude           (ping_time) float64 3kB dask.array<chunksize=(344,), meta=np.ndarray>
    longitude          (ping_time) float64 3kB dask.array<chunksize=(344,), meta=np.ndarray>
Attributes:
    processing_function:          commongrid.compute_MVBS
    processing_level:             Level 3A
    processing_level_url:         https://echopype.readthedocs.io/en/stable/p...
    processing_software_name:     echopype
    processing_software_version:  0.9.0
    processing_time:              2024-08-14T00:14:32Z

In [13]:
# Values are in seconds since a time reference (ds['ping_time'].attrs['units'])'
# How to determine 'max_seconds'?
# Values differ everytime
ds['ping_time'].values

array([                   0,  3782820132520198796,           5807067136,
        3028958878108044837,   864973762930821254,  3461915200917078021,
         149469828309255689,   217880530152149845,  8603368468337132629,
        3564992126555343392,   505622529647456276,  8747524786399873811,
        3467263160835719968,  1518568513076397596,  5928236109583968340,
        7299807592561594964,  3471766700300400500,  2671482321101850156,
        8319681593119953749,  7296711286213189748,  8386093285481477234,
        7526769799820373865,  1665822210375905903,  3472330516725969421,
         943321809970802736,  3689073928278389555,  3551422945223326005,
         433564935608938507,  1166452306549735955,  5262758573302416134,
        3635642324234892398,   312159074083939889,  7885595613501133571,
        2324230494896418669,  8243086091055548233,  3684016251752047990,
         650221698729214512,    72354425775621674,    40252579577332993,
       -9150890020423237072, -8471026814169993984,  7306774976605756238,
       -5173845376839195792, -1330692225854466534,  8094695286994480468,
       -1170278700699484599,  3949757382583639562,  5133173896612215022,
        5378867142962074127,  4093748158192996355,  8350475890930934510,
       -4753277688425358826, -4848378126618963368,  4709697027361527360,
        3027465316345048822,  6918842682138677067, -5914756772212206948,
       -2983858970889280582, -9018916060794810272,  3213822973607226957,
       -6393061157381937212, -3880605395208163652,  4448934993843304104,
       -2993971165628306288,  2733414907326038518, -5353520431740917821,
        -674096307682721057, -3971408004739914275,  7294342154157279597,
       -6593047774982643447, -7725542016319908742, -8759533347410133846,
        4649261154497610004, -6751183251634806892, -3456766885962209859,
        5865814485701055636, -1141024391878842402,  4133605648827029922,
       -8619731141887623789, -7442875732715251956, -4406371024372744659,
        1062423413601715415, -1801225636628626252, -8613810974431924135,
        5115874976305645452,  2965478884741619671, -6729614593677097676,
       -7321438801216724290, -9033375328046480779,  2247431460467277569,
        3465524462124073734, -6171409811552042986, -7216770461566285269,
        3516016100165983680,  1586408487884359197,  8877126639240483844,
        6118957819903764415,  1022569761465194479,   -71774954632969466,
        1310694830451655684,   -71774937453100282,   215892411047479300,
        2113598924914688001,  3100735027220448293,   432630367888146694,
         218148626000915208,  2314099255015452674,   866395578310863364,
          82100537608177195,   722278190571324164,   145607188952942122,
       -9122315897238716158,   217949799096385804,  3478802327326891349,
        7511870319897059397,  8242483622908556404,  8247342597676543596,
        3417510164015903605,  8319681593119953749,  8390880395277849204,
        8028075772393121385,  7598258015748571502,  8156138163714029940,
         505816035105638406,  4192960312586273025,   505816035105638406,
        8103229620352320048,  8443814386005389114,  8391179665161741683,
        4995430073871852334,  6003989292478780498,  7146721415796965697,
         444457810712884338,  1839158803615253761,  8011674190156690536,
        8243121640099050339,  8026310038592516724,                  109,
                          0,                    0,                    0,
                          0,                    0,                    0,
                          0,           4592752496,           4301501480,
                 4301958216,           4304144496,           4301427200,
                 4308059056,           4357359472,           4317506928,
                 4311699248,           4616105392,           4581691696,
                 4304144496,           4301734304,           4581693168,
                 4304144496,           4301490288,           4616101360,
                 4301944208,           4616008304,           4616000176,
                 4616006768,           4616001648,           4616004592,
                 4616108400,           4301726584,           4301954408,
                 4301911168,           4301950048,           4616010480,
                 4301932600,           4581691696,           4581693168,
                 4581691696,           4301441224,           4626917360,
                 4581693168,           4301441224,           4626917392,
                 4308059056,           4341490480,           4616101360,
                 4530964976,           4333878320,           4616106736,
                 4573029424,           4333912944,           4301910160,
                 5806966272,  -488002352241966424,                    0,
        3028958878102795660,   864973762930821254,   662041452371509253,
        5116673043209716486,  6125746623405044034,  7018141243897808900,
        7164771041077781876,  1166839558536652136,   866666216461569584,
        7237970036833473287,   312159073882610225,  7237123450841664522,
        7883916324106346607,  2247332710079362153,  4690512219003486982,
        7598824250524320065,  5989899054927276390,  3491245613787804261,
        3545230353864922910,  6498747245820653618,  3545232518648302871,
        3484160162480337714,   217871733924923521,  3554277998322910293,
         577680123685318675,  7298681843280120339,  1310569694287459186,
        5335379104408863494,  7584941903187243621,   217892624964614516,
        7307182844899099733,  6148069153641288992,  8032016438889829459,
         217910217419090802,  4995430029405127765,  5917857949605319762,
        7598824250524320083,  7957695015157983590,  7598258015748571424,
         950296915544668532,  1006420687787264262,   180710233667076353,
       -9078682892935102449,  3897695132643754242,  6317653844660306702,
       -5959156039005932019,   670227837862642512, -3702088847127387091,
       -1018726316747478723,  3103305837000962515, -5469275690010813881,
        4783847126012372575,  -535599345426073930,   689086025822138338,
       -7947700188873170370, -1078995291171691820,   -91131773304825720,
        2298232718351659027,  5073043048731301006, -4882091023908777720,
       -7127228312966988237,  7397063661930528024, -3120600771190099256,
       -3681628576882132837,   409825696148151536, -3530901984198576746,
       -2498100630989095431, -8481212351535454264, -3873904131087639369,
        7379213404721128063, -7254377273910410239, -8054877330520711117,
       -2598766362130955405, -8328343830789816662, -2171002443228343456,
       -7676296248528425422, -3455107167740327065,  7720900337034006377,
        4860503607574228275,  8946877189162172133, -4535753155570072526,
        9066779672853894291,  6644335823194662711,   813367961801146843,
       -8186819503418451745, -5150766089171409227, -7060842606348714063,
         390673509103964907, -2132532710024520023,  5535911697754952680,
       -6020215530934506061,  8382665375878036259, -7890559055631464183,
        9018162547765929526,  2757307748069100828,  4919242786936569808,
        2256477717445188084,  3414701573503734871,  3333324419230945457,
        6433152308469307971,  5352007901619553530,  -236587694238301872,
        1089453672454231399,  6151871712023139939,  2667265850529868334,
       -7544388467366643655, -1157999796405991652,    72058706469028399,
        2247559552208896419,  3465524462124073734,  4477433525352824854,
       -1213245235442224746,  3509610539191870850,  1586408487884359197,
        3146427068092453892, -4567818934004953270,  1022540754422264477,
         -71774954632969466,  1094522048337871876,   -71774937453100282,
        3530541736741831940,   721737150638523921,  2113600024040441904,
        2113598925552222240, -6901713402469809121,  8391446571907326006,
        3345174393548388976,  7017575121530220387,  4702111157906793262,
        7163369285420737859,  7599387200750711905,  3489289581611935075,
         361696471076570676,  3469513511359545607,   361696471076570660,
        8391446460234805255,  8102929483753798256,  7165055961909912366,
               470020206177,                    0,                    0,
                          0,                    0,           4317506928,
       -2119288192161535383,           4581691696,  7821588457340296746,
                          0,                    0])

In [14]:
ds['ping_time'].attrs

{'axis': 'T',
 'calendar': 'proleptic_gregorian',
 'long_name': 'Ping time',
 'standard_name': 'time',
 'units': 'seconds since 2017-07-31 18:08:45'}

### Normal
Example file: ```2017/x0027_0_wt_20170709_214828_f0003.zarr```

Load from s3

In [15]:
# test loading a zarr file

bucket = "agr230002-bucket01"
zarr_key = "hake_data/data_zarr/MVBS/2017/x0027_0_wt_20170709_214828_f0003.zarr"
full_path = f"s3://{bucket}/{zarr_key}"

s3_ds_norm = xr.open_zarr(fs.get_mapper(full_path))
s3_ds_norm

<xarray.Dataset> Size: 14MB
Dimensions:            (channel: 3, ping_time: 748, depth: 759)
Coordinates:
  * channel            (channel) <U37 444B 'GPT  18 kHz 009072058c8d 1-1 ES18...
  * depth              (depth) float64 6kB 0.0 1.0 2.0 3.0 ... 756.0 757.0 758.0
  * ping_time          (ping_time) datetime64[ns] 6kB 2017-07-09T21:48:25 ......
Data variables:
    Sv                 (channel, ping_time, depth) float64 14MB dask.array<chunksize=(3, 748, 759), meta=np.ndarray>
    frequency_nominal  (channel) float64 24B dask.array<chunksize=(3,), meta=np.ndarray>
    latitude           (ping_time) float64 6kB dask.array<chunksize=(748,), meta=np.ndarray>
    longitude          (ping_time) float64 6kB dask.array<chunksize=(748,), meta=np.ndarray>
Attributes:
    processing_function:          commongrid.compute_MVBS
    processing_level:             Level 3A
    processing_level_url:         https://echopype.readthedocs.io/en/stable/p...
    processing_software_name:     echopype
    processing_software_version:  0.9.0
    processing_time:              2024-08-14T00:26:30Z

In [16]:
s3_ds_norm['ping_time'].values

array(['2017-07-09T21:48:25.000000000', '2017-07-09T21:48:30.000000000',
       '2017-07-09T21:48:35.000000000', '2017-07-09T21:48:40.000000000',
       '2017-07-09T21:48:45.000000000', '2017-07-09T21:48:50.000000000',
       '2017-07-09T21:48:55.000000000', '2017-07-09T21:49:00.000000000',
       '2017-07-09T21:49:05.000000000', '2017-07-09T21:49:10.000000000',
       '2017-07-09T21:49:15.000000000', '2017-07-09T21:49:20.000000000',
       '2017-07-09T21:49:25.000000000', '2017-07-09T21:49:30.000000000',
       '2017-07-09T21:49:35.000000000', '2017-07-09T21:49:40.000000000',
       '2017-07-09T21:49:45.000000000', '2017-07-09T21:49:50.000000000',
       '2017-07-09T21:49:55.000000000', '2017-07-09T21:50:00.000000000',
       '2017-07-09T21:50:05.000000000', '2017-07-09T21:50:10.000000000',
       '2017-07-09T21:50:15.000000000', '2017-07-09T21:50:20.000000000',
       '2017-07-09T21:50:25.000000000', '2017-07-09T21:50:30.000000000',
       '2017-07-09T21:50:35.000000000', '2017-07-09T21:50:40.000000000',
       '2017-07-09T21:50:45.000000000', '2017-07-09T21:50:50.000000000',
       '2017-07-09T21:50:55.000000000', '2017-07-09T21:51:00.000000000',
       '2017-07-09T21:51:05.000000000', '2017-07-09T21:51:10.000000000',
       '2017-07-09T21:51:15.000000000', '2017-07-09T21:51:20.000000000',
       '2017-07-09T21:51:25.000000000', '2017-07-09T21:51:30.000000000',
       '2017-07-09T21:51:35.000000000', '2017-07-09T21:51:40.000000000',
       '2017-07-09T21:51:45.000000000', '2017-07-09T21:51:50.000000000',
       '2017-07-09T21:51:55.000000000', '2017-07-09T21:52:00.000000000',
       '2017-07-09T21:52:05.000000000', '2017-07-09T21:52:10.000000000',
       '2017-07-09T21:52:15.000000000', '2017-07-09T21:52:20.000000000',
       '2017-07-09T21:52:25.000000000', '2017-07-09T21:52:30.000000000',
       '2017-07-09T21:52:35.000000000', '2017-07-09T21:52:40.000000000',
       '2017-07-09T21:52:45.000000000', '2017-07-09T21:52:50.000000000',
       '2017-07-09T21:52:55.000000000', '2017-07-09T21:53:00.000000000',
       '2017-07-09T21:53:05.000000000', '2017-07-09T21:53:10.000000000',
       '2017-07-09T21:53:15.000000000', '2017-07-09T21:53:20.000000000',
       '2017-07-09T21:53:25.000000000', '2017-07-09T21:53:30.000000000',
       '2017-07-09T21:53:35.000000000', '2017-07-09T21:53:40.000000000',
       '2017-07-09T21:53:45.000000000', '2017-07-09T21:53:50.000000000',
       '2017-07-09T21:53:55.000000000', '2017-07-09T21:54:00.000000000',
       '2017-07-09T21:54:05.000000000', '2017-07-09T21:54:10.000000000',
       '2017-07-09T21:54:15.000000000', '2017-07-09T21:54:20.000000000',
       '2017-07-09T21:54:25.000000000', '2017-07-09T21:54:30.000000000',
       '2017-07-09T21:54:35.000000000', '2017-07-09T21:54:40.000000000',
       '2017-07-09T21:54:45.000000000', '2017-07-09T21:54:50.000000000',
       '2017-07-09T21:54:55.000000000', '2017-07-09T21:55:00.000000000',
       '2017-07-09T21:55:05.000000000', '2017-07-09T21:55:10.000000000',
       '2017-07-09T21:55:15.000000000', '2017-07-09T21:55:20.000000000',
       '2017-07-09T21:55:25.000000000', '2017-07-09T21:55:30.000000000',
       '2017-07-09T21:55:35.000000000', '2017-07-09T21:55:40.000000000',
       '2017-07-09T21:55:45.000000000', '2017-07-09T21:55:50.000000000',
       '2017-07-09T21:55:55.000000000', '2017-07-09T21:56:00.000000000',
       '2017-07-09T21:56:05.000000000', '2017-07-09T21:56:10.000000000',
       '2017-07-09T21:56:15.000000000', '2017-07-09T21:56:20.000000000',
       '2017-07-09T21:56:25.000000000', '2017-07-09T21:56:30.000000000',
       '2017-07-09T21:56:35.000000000', '2017-07-09T21:56:40.000000000',
       '2017-07-09T21:56:45.000000000', '2017-07-09T21:56:50.000000000',
       '2017-07-09T21:56:55.000000000', '2017-07-09T21:57:00.000000000',
       '2017-07-09T21:57:05.000000000', '2017-07-09T21:57:10.000000000',
       '2017-07-09T21:57:15.000000000', '2017-07-09T21:57:20.000000000',
       '2017-07-09T21:57:25.000000000', '2017-07-09T21:57:30.000000000',
       '2017-07-09T21:57:35.000000000', '2017-07-09T21:57:40.000000000',
       '2017-07-09T21:57:45.000000000', '2017-07-09T21:57:50.000000000',
       '2017-07-09T21:57:55.000000000', '2017-07-09T21:58:00.000000000',
       '2017-07-09T21:58:05.000000000', '2017-07-09T21:58:10.000000000',
       '2017-07-09T21:58:15.000000000', '2017-07-09T21:58:20.000000000',
       '2017-07-09T21:58:25.000000000', '2017-07-09T21:58:30.000000000',
       '2017-07-09T21:58:35.000000000', '2017-07-09T21:58:40.000000000',
       '2017-07-09T21:58:45.000000000', '2017-07-09T21:58:50.000000000',
       '2017-07-09T21:58:55.000000000', '2017-07-09T21:59:00.000000000',
       '2017-07-09T21:59:05.000000000', '2017-07-09T21:59:10.000000000',
       '2017-07-09T21:59:15.000000000', '2017-07-09T21:59:20.000000000',
       '2017-07-09T21:59:25.000000000', '2017-07-09T21:59:30.000000000',
       '2017-07-09T21:59:35.000000000', '2017-07-09T21:59:40.000000000',
       '2017-07-09T21:59:45.000000000', '2017-07-09T21:59:50.000000000',
       '2017-07-09T21:59:55.000000000', '2017-07-09T22:00:00.000000000',
       '2017-07-09T22:00:05.000000000', '2017-07-09T22:00:10.000000000',
       '2017-07-09T22:00:15.000000000', '2017-07-09T22:00:20.000000000',
       '2017-07-09T22:00:25.000000000', '2017-07-09T22:00:30.000000000',
       '2017-07-09T22:00:35.000000000', '2017-07-09T22:00:40.000000000',
       '2017-07-09T22:00:45.000000000', '2017-07-09T22:00:50.000000000',
       '2017-07-09T22:00:55.000000000', '2017-07-09T22:01:00.000000000',
       '2017-07-09T22:01:05.000000000', '2017-07-09T22:01:10.000000000',
       '2017-07-09T22:01:15.000000000', '2017-07-09T22:01:20.000000000',
       '2017-07-09T22:01:25.000000000', '2017-07-09T22:01:30.000000000',
       '2017-07-09T22:01:35.000000000', '2017-07-09T22:01:40.000000000',
       '2017-07-09T22:01:45.000000000', '2017-07-09T22:01:50.000000000',
       '2017-07-09T22:01:55.000000000', '2017-07-09T22:02:00.000000000',
       '2017-07-09T22:02:05.000000000', '2017-07-09T22:02:10.000000000',
       '2017-07-09T22:02:15.000000000', '2017-07-09T22:02:20.000000000',
       '2017-07-09T22:02:25.000000000', '2017-07-09T22:02:30.000000000',
       '2017-07-09T22:02:35.000000000', '2017-07-09T22:02:40.000000000',
       '2017-07-09T22:02:45.000000000', '2017-07-09T22:02:50.000000000',
       '2017-07-09T22:02:55.000000000', '2017-07-09T22:03:00.000000000',
       '2017-07-09T22:03:05.000000000', '2017-07-09T22:03:10.000000000',
       '2017-07-09T22:03:15.000000000', '2017-07-09T22:03:20.000000000',
       '2017-07-09T22:03:25.000000000', '2017-07-09T22:03:30.000000000',
       '2017-07-09T22:03:35.000000000', '2017-07-09T22:03:40.000000000',
       '2017-07-09T22:03:45.000000000', '2017-07-09T22:03:50.000000000',
       '2017-07-09T22:03:55.000000000', '2017-07-09T22:04:00.000000000',
       '2017-07-09T22:04:05.000000000', '2017-07-09T22:04:10.000000000',
       '2017-07-09T22:04:15.000000000', '2017-07-09T22:04:20.000000000',
       '2017-07-09T22:04:25.000000000', '2017-07-09T22:04:30.000000000',
       '2017-07-09T22:04:35.000000000', '2017-07-09T22:04:40.000000000',
       '2017-07-09T22:04:45.000000000', '2017-07-09T22:04:50.000000000',
       '2017-07-09T22:04:55.000000000', '2017-07-09T22:05:00.000000000',
       '2017-07-09T22:05:05.000000000', '2017-07-09T22:05:10.000000000',
       '2017-07-09T22:05:15.000000000', '2017-07-09T22:05:20.000000000',
       '2017-07-09T22:05:25.000000000', '2017-07-09T22:05:30.000000000',
       '2017-07-09T22:05:35.000000000', '2017-07-09T22:05:40.000000000',
       '2017-07-09T22:05:45.000000000', '2017-07-09T22:05:50.000000000',
       '2017-07-09T22:05:55.000000000', '2017-07-09T22:06:00.000000000',
       '2017-07-09T22:06:05.000000000', '2017-07-09T22:06:10.000000000',
       '2017-07-09T22:06:15.000000000', '2017-07-09T22:06:20.000000000',
       '2017-07-09T22:06:25.000000000', '2017-07-09T22:06:30.000000000',
       '2017-07-09T22:06:35.000000000', '2017-07-09T22:06:40.000000000',
       '2017-07-09T22:06:45.000000000', '2017-07-09T22:06:50.000000000',
       '2017-07-09T22:06:55.000000000', '2017-07-09T22:07:00.000000000',
       '2017-07-09T22:07:05.000000000', '2017-07-09T22:07:10.000000000',
       '2017-07-09T22:07:15.000000000', '2017-07-09T22:07:20.000000000',
       '2017-07-09T22:07:25.000000000', '2017-07-09T22:07:30.000000000',
       '2017-07-09T22:07:35.000000000', '2017-07-09T22:07:40.000000000',
       '2017-07-09T22:07:45.000000000', '2017-07-09T22:07:50.000000000',
       '2017-07-09T22:07:55.000000000', '2017-07-09T22:08:00.000000000',
       '2017-07-09T22:08:05.000000000', '2017-07-09T22:08:10.000000000',
       '2017-07-09T22:08:15.000000000', '2017-07-09T22:08:20.000000000',
       '2017-07-09T22:08:25.000000000', '2017-07-09T22:08:30.000000000',
       '2017-07-09T22:08:35.000000000', '2017-07-09T22:08:40.000000000',
       '2017-07-09T22:08:45.000000000', '2017-07-09T22:08:50.000000000',
       '2017-07-09T22:08:55.000000000', '2017-07-09T22:09:00.000000000',
       '2017-07-09T22:09:05.000000000', '2017-07-09T22:09:10.000000000',
       '2017-07-09T22:09:15.000000000', '2017-07-09T22:09:20.000000000',
       '2017-07-09T22:09:25.000000000', '2017-07-09T22:09:30.000000000',
       '2017-07-09T22:09:35.000000000', '2017-07-09T22:09:40.000000000',
       '2017-07-09T22:09:45.000000000', '2017-07-09T22:09:50.000000000',
       '2017-07-09T22:09:55.000000000', '2017-07-09T22:10:00.000000000',
       '2017-07-09T22:10:05.000000000', '2017-07-09T22:10:10.000000000',
       '2017-07-09T22:10:15.000000000', '2017-07-09T22:10:20.000000000',
       '2017-07-09T22:10:25.000000000', '2017-07-09T22:10:30.000000000',
       '2017-07-09T22:10:35.000000000', '2017-07-09T22:10:40.000000000',
       '2017-07-09T22:10:45.000000000', '2017-07-09T22:10:50.000000000',
       '2017-07-09T22:10:55.000000000', '2017-07-09T22:11:00.000000000',
       '2017-07-09T22:11:05.000000000', '2017-07-09T22:11:10.000000000',
       '2017-07-09T22:11:15.000000000', '2017-07-09T22:11:20.000000000',
       '2017-07-09T22:11:25.000000000', '2017-07-09T22:11:30.000000000',
       '2017-07-09T22:11:35.000000000', '2017-07-09T22:11:40.000000000',
       '2017-07-09T22:11:45.000000000', '2017-07-09T22:11:50.000000000',
       '2017-07-09T22:11:55.000000000', '2017-07-09T22:12:00.000000000',
       '2017-07-09T22:12:05.000000000', '2017-07-09T22:12:10.000000000',
       '2017-07-09T22:12:15.000000000', '2017-07-09T22:12:20.000000000',
       '2017-07-09T22:12:25.000000000', '2017-07-09T22:12:30.000000000',
       '2017-07-09T22:12:35.000000000', '2017-07-09T22:12:40.000000000',
       '2017-07-09T22:12:45.000000000', '2017-07-09T22:12:50.000000000',
       '2017-07-09T22:12:55.000000000', '2017-07-09T22:13:00.000000000',
       '2017-07-09T22:13:05.000000000', '2017-07-09T22:13:10.000000000',
       '2017-07-09T22:13:15.000000000', '2017-07-09T22:13:20.000000000',
       '2017-07-09T22:13:25.000000000', '2017-07-09T22:13:30.000000000',
       '2017-07-09T22:13:35.000000000', '2017-07-09T22:13:40.000000000',
       '2017-07-09T22:13:45.000000000', '2017-07-09T22:13:50.000000000',
       '2017-07-09T22:13:55.000000000', '2017-07-09T22:14:00.000000000',
       '2017-07-09T22:14:05.000000000', '2017-07-09T22:14:10.000000000',
       '2017-07-09T22:14:15.000000000', '2017-07-09T22:14:20.000000000',
       '2017-07-09T22:14:25.000000000', '2017-07-09T22:14:30.000000000',
       '2017-07-09T22:14:35.000000000', '2017-07-09T22:14:40.000000000',
       '2017-07-09T22:14:45.000000000', '2017-07-09T22:14:50.000000000',
       '2017-07-09T22:14:55.000000000', '2017-07-09T22:15:00.000000000',
       '2017-07-09T22:15:05.000000000', '2017-07-09T22:15:10.000000000',
       '2017-07-09T22:15:15.000000000', '2017-07-09T22:15:20.000000000',
       '2017-07-09T22:15:25.000000000', '2017-07-09T22:15:30.000000000',
       '2017-07-09T22:15:35.000000000', '2017-07-09T22:15:40.000000000',
       '2017-07-09T22:15:45.000000000', '2017-07-09T22:15:50.000000000',
       '2017-07-09T22:15:55.000000000', '2017-07-09T22:16:00.000000000',
       '2017-07-09T22:16:05.000000000', '2017-07-09T22:16:10.000000000',
       '2017-07-09T22:16:15.000000000', '2017-07-09T22:16:20.000000000',
       '2017-07-09T22:16:25.000000000', '2017-07-09T22:16:30.000000000',
       '2017-07-09T22:16:35.000000000', '2017-07-09T22:16:40.000000000',
       '2017-07-09T22:16:45.000000000', '2017-07-09T22:16:50.000000000',
       '2017-07-09T22:16:55.000000000', '2017-07-09T22:17:00.000000000',
       '2017-07-09T22:17:05.000000000', '2017-07-09T22:17:10.000000000',
       '2017-07-09T22:17:15.000000000', '2017-07-09T22:17:20.000000000',
       '2017-07-09T22:17:25.000000000', '2017-07-09T22:17:30.000000000',
       '2017-07-09T22:17:35.000000000', '2017-07-09T22:17:40.000000000',
       '2017-07-09T22:17:45.000000000', '2017-07-09T22:17:50.000000000',
       '2017-07-09T22:17:55.000000000', '2017-07-09T22:18:00.000000000',
       '2017-07-09T22:18:05.000000000', '2017-07-09T22:18:10.000000000',
       '2017-07-09T22:18:15.000000000', '2017-07-09T22:18:20.000000000',
       '2017-07-09T22:18:25.000000000', '2017-07-09T22:18:30.000000000',
       '2017-07-09T22:18:35.000000000', '2017-07-09T22:18:40.000000000',
       '2017-07-09T22:18:45.000000000', '2017-07-09T22:18:50.000000000',
       '2017-07-09T22:18:55.000000000', '2017-07-09T22:19:00.000000000',
       '2017-07-09T22:19:05.000000000', '2017-07-09T22:19:10.000000000',
       '2017-07-09T22:19:15.000000000', '2017-07-09T22:19:20.000000000',
       '2017-07-09T22:19:25.000000000', '2017-07-09T22:19:30.000000000',
       '2017-07-09T22:19:35.000000000', '2017-07-09T22:19:40.000000000',
       '2017-07-09T22:19:45.000000000', '2017-07-09T22:19:50.000000000',
       '2017-07-09T22:19:55.000000000', '2017-07-09T22:20:00.000000000',
       '2017-07-09T22:20:05.000000000', '2017-07-09T22:20:10.000000000',
       '2017-07-09T22:20:15.000000000', '2017-07-09T22:20:20.000000000',
       '2017-07-09T22:20:25.000000000', '2017-07-09T22:20:30.000000000',
       '2017-07-09T22:20:35.000000000', '2017-07-09T22:20:40.000000000',
       '2017-07-09T22:20:45.000000000', '2017-07-09T22:20:50.000000000',
       '2017-07-09T22:20:55.000000000', '2017-07-09T22:21:00.000000000',
       '2017-07-09T22:21:05.000000000', '2017-07-09T22:21:10.000000000',
       '2017-07-09T22:21:15.000000000', '2017-07-09T22:21:20.000000000',
       '2017-07-09T22:21:25.000000000', '2017-07-09T22:21:30.000000000',
       '2017-07-09T22:21:35.000000000', '2017-07-09T22:21:40.000000000',
       '2017-07-09T22:21:45.000000000', '2017-07-09T22:21:50.000000000',
       '2017-07-09T22:21:55.000000000', '2017-07-09T22:22:00.000000000',
       '2017-07-09T22:22:05.000000000', '2017-07-09T22:22:10.000000000',
       '2017-07-09T22:22:15.000000000', '2017-07-09T22:22:20.000000000',
       '2017-07-09T22:22:25.000000000', '2017-07-09T22:22:30.000000000',
       '2017-07-09T22:22:35.000000000', '2017-07-09T22:22:40.000000000',
       '2017-07-09T22:22:45.000000000', '2017-07-09T22:22:50.000000000',
       '2017-07-09T22:22:55.000000000', '2017-07-09T22:23:00.000000000',
       '2017-07-09T22:23:05.000000000', '2017-07-09T22:23:10.000000000',
       '2017-07-09T22:23:15.000000000', '2017-07-09T22:23:20.000000000',
       '2017-07-09T22:23:25.000000000', '2017-07-09T22:23:30.000000000',
       '2017-07-09T22:23:35.000000000', '2017-07-09T22:23:40.000000000',
       '2017-07-09T22:23:45.000000000', '2017-07-09T22:23:50.000000000',
       '2017-07-09T22:23:55.000000000', '2017-07-09T22:24:00.000000000',
       '2017-07-09T22:24:05.000000000', '2017-07-09T22:24:10.000000000',
       '2017-07-09T22:24:15.000000000', '2017-07-09T22:24:20.000000000',
       '2017-07-09T22:24:25.000000000', '2017-07-09T22:24:30.000000000',
       '2017-07-09T22:24:35.000000000', '2017-07-09T22:24:40.000000000',
       '2017-07-09T22:24:45.000000000', '2017-07-09T22:24:50.000000000',
       '2017-07-09T22:24:55.000000000', '2017-07-09T22:25:00.000000000',
       '2017-07-09T22:25:05.000000000', '2017-07-09T22:25:10.000000000',
       '2017-07-09T22:25:15.000000000', '2017-07-09T22:25:20.000000000',
       '2017-07-09T22:25:25.000000000', '2017-07-09T22:25:30.000000000',
       '2017-07-09T22:25:35.000000000', '2017-07-09T22:25:40.000000000',
       '2017-07-09T22:25:45.000000000', '2017-07-09T22:25:50.000000000',
       '2017-07-09T22:25:55.000000000', '2017-07-09T22:26:00.000000000',
       '2017-07-09T22:26:05.000000000', '2017-07-09T22:26:10.000000000',
       '2017-07-09T22:26:15.000000000', '2017-07-09T22:26:20.000000000',
       '2017-07-09T22:26:25.000000000', '2017-07-09T22:26:30.000000000',
       '2017-07-09T22:26:35.000000000', '2017-07-09T22:26:40.000000000',
       '2017-07-09T22:26:45.000000000', '2017-07-09T22:26:50.000000000',
       '2017-07-09T22:26:55.000000000', '2017-07-09T22:27:00.000000000',
       '2017-07-09T22:27:05.000000000', '2017-07-09T22:27:10.000000000',
       '2017-07-09T22:27:15.000000000', '2017-07-09T22:27:20.000000000',
       '2017-07-09T22:27:25.000000000', '2017-07-09T22:27:30.000000000',
       '2017-07-09T22:27:35.000000000', '2017-07-09T22:27:40.000000000',
       '2017-07-09T22:27:45.000000000', '2017-07-09T22:27:50.000000000',
       '2017-07-09T22:27:55.000000000', '2017-07-09T22:28:00.000000000',
       '2017-07-09T22:28:05.000000000', '2017-07-09T22:28:10.000000000',
       '2017-07-09T22:28:15.000000000', '2017-07-09T22:28:20.000000000',
       '2017-07-09T22:28:25.000000000', '2017-07-09T22:28:30.000000000',
       '2017-07-09T22:28:35.000000000', '2017-07-09T22:28:40.000000000',
       '2017-07-09T22:28:45.000000000', '2017-07-09T22:28:50.000000000',
       '2017-07-09T22:28:55.000000000', '2017-07-09T22:29:00.000000000',
       '2017-07-09T22:29:05.000000000', '2017-07-09T22:29:10.000000000',
       '2017-07-09T22:29:15.000000000', '2017-07-09T22:29:20.000000000',
       '2017-07-09T22:29:25.000000000', '2017-07-09T22:29:30.000000000',
       '2017-07-09T22:29:35.000000000', '2017-07-09T22:29:40.000000000',
       '2017-07-09T22:29:45.000000000', '2017-07-09T22:29:50.000000000',
       '2017-07-09T22:29:55.000000000', '2017-07-09T22:30:00.000000000',
       '2017-07-09T22:30:05.000000000', '2017-07-09T22:30:10.000000000',
       '2017-07-09T22:30:15.000000000', '2017-07-09T22:30:20.000000000',
       '2017-07-09T22:30:25.000000000', '2017-07-09T22:30:30.000000000',
       '2017-07-09T22:30:35.000000000', '2017-07-09T22:30:40.000000000',
       '2017-07-09T22:30:45.000000000', '2017-07-09T22:30:50.000000000',
       '2017-07-09T22:30:55.000000000', '2017-07-09T22:31:00.000000000',
       '2017-07-09T22:31:05.000000000', '2017-07-09T22:31:10.000000000',
       '2017-07-09T22:31:15.000000000', '2017-07-09T22:31:20.000000000',
       '2017-07-09T22:31:25.000000000', '2017-07-09T22:31:30.000000000',
       '2017-07-09T22:31:35.000000000', '2017-07-09T22:31:40.000000000',
       '2017-07-09T22:31:45.000000000', '2017-07-09T22:31:50.000000000',
       '2017-07-09T22:31:55.000000000', '2017-07-09T22:32:00.000000000',
       '2017-07-09T22:32:05.000000000', '2017-07-09T22:32:10.000000000',
       '2017-07-09T22:32:15.000000000', '2017-07-09T22:32:20.000000000',
       '2017-07-09T22:32:25.000000000', '2017-07-09T22:32:30.000000000',
       '2017-07-09T22:32:35.000000000', '2017-07-09T22:32:40.000000000',
       '2017-07-09T22:32:45.000000000', '2017-07-09T22:32:50.000000000',
       '2017-07-09T22:32:55.000000000', '2017-07-09T22:33:00.000000000',
       '2017-07-09T22:33:05.000000000', '2017-07-09T22:33:10.000000000',
       '2017-07-09T22:33:15.000000000', '2017-07-09T22:33:20.000000000',
       '2017-07-09T22:33:25.000000000', '2017-07-09T22:33:30.000000000',
       '2017-07-09T22:33:35.000000000', '2017-07-09T22:33:40.000000000',
       '2017-07-09T22:33:45.000000000', '2017-07-09T22:33:50.000000000',

Load from local

In [17]:
ds_norm = xr.open_zarr('mvbs_sample/2017/x0027_0_wt_20170709_214828_f0003.zarr')
ds_norm

<xarray.Dataset> Size: 14MB
Dimensions:            (channel: 3, ping_time: 748, depth: 759)
Coordinates:
  * channel            (channel) <U37 444B 'GPT  18 kHz 009072058c8d 1-1 ES18...
  * depth              (depth) float64 6kB 0.0 1.0 2.0 3.0 ... 756.0 757.0 758.0
  * ping_time          (ping_time) datetime64[ns] 6kB 2017-07-09T21:48:25 ......
Data variables:
    Sv                 (channel, ping_time, depth) float64 14MB dask.array<chunksize=(3, 748, 759), meta=np.ndarray>
    frequency_nominal  (channel) float64 24B dask.array<chunksize=(3,), meta=np.ndarray>
    latitude           (ping_time) float64 6kB dask.array<chunksize=(748,), meta=np.ndarray>
    longitude          (ping_time) float64 6kB dask.array<chunksize=(748,), meta=np.ndarray>
Attributes:
    processing_function:          commongrid.compute_MVBS
    processing_level:             Level 3A
    processing_level_url:         https://echopype.readthedocs.io/en/stable/p...
    processing_software_name:     echopype
    processing_software_version:  0.9.0
    processing_time:              2024-08-14T00:26:30Z

In [18]:
ds_norm['ping_time'].values

array(['2017-07-09T21:48:25.000000000', '2017-07-09T21:48:30.000000000',
       '2017-07-09T21:48:35.000000000', '2017-07-09T21:48:40.000000000',
       '2017-07-09T21:48:45.000000000', '2017-07-09T21:48:50.000000000',
       '2017-07-09T21:48:55.000000000', '2017-07-09T21:49:00.000000000',
       '2017-07-09T21:49:05.000000000', '2017-07-09T21:49:10.000000000',
       '2017-07-09T21:49:15.000000000', '2017-07-09T21:49:20.000000000',
       '2017-07-09T21:49:25.000000000', '2017-07-09T21:49:30.000000000',
       '2017-07-09T21:49:35.000000000', '2017-07-09T21:49:40.000000000',
       '2017-07-09T21:49:45.000000000', '2017-07-09T21:49:50.000000000',
       '2017-07-09T21:49:55.000000000', '2017-07-09T21:50:00.000000000',
       '2017-07-09T21:50:05.000000000', '2017-07-09T21:50:10.000000000',
       '2017-07-09T21:50:15.000000000', '2017-07-09T21:50:20.000000000',
       '2017-07-09T21:50:25.000000000', '2017-07-09T21:50:30.000000000',
       '2017-07-09T21:50:35.000000000', '2017-07-09T21:50:40.000000000',
       '2017-07-09T21:50:45.000000000', '2017-07-09T21:50:50.000000000',
       '2017-07-09T21:50:55.000000000', '2017-07-09T21:51:00.000000000',
       '2017-07-09T21:51:05.000000000', '2017-07-09T21:51:10.000000000',
       '2017-07-09T21:51:15.000000000', '2017-07-09T21:51:20.000000000',
       '2017-07-09T21:51:25.000000000', '2017-07-09T21:51:30.000000000',
       '2017-07-09T21:51:35.000000000', '2017-07-09T21:51:40.000000000',
       '2017-07-09T21:51:45.000000000', '2017-07-09T21:51:50.000000000',
       '2017-07-09T21:51:55.000000000', '2017-07-09T21:52:00.000000000',
       '2017-07-09T21:52:05.000000000', '2017-07-09T21:52:10.000000000',
       '2017-07-09T21:52:15.000000000', '2017-07-09T21:52:20.000000000',
       '2017-07-09T21:52:25.000000000', '2017-07-09T21:52:30.000000000',
       '2017-07-09T21:52:35.000000000', '2017-07-09T21:52:40.000000000',
       '2017-07-09T21:52:45.000000000', '2017-07-09T21:52:50.000000000',
       '2017-07-09T21:52:55.000000000', '2017-07-09T21:53:00.000000000',
       '2017-07-09T21:53:05.000000000', '2017-07-09T21:53:10.000000000',
       '2017-07-09T21:53:15.000000000', '2017-07-09T21:53:20.000000000',
       '2017-07-09T21:53:25.000000000', '2017-07-09T21:53:30.000000000',
       '2017-07-09T21:53:35.000000000', '2017-07-09T21:53:40.000000000',
       '2017-07-09T21:53:45.000000000', '2017-07-09T21:53:50.000000000',
       '2017-07-09T21:53:55.000000000', '2017-07-09T21:54:00.000000000',
       '2017-07-09T21:54:05.000000000', '2017-07-09T21:54:10.000000000',
       '2017-07-09T21:54:15.000000000', '2017-07-09T21:54:20.000000000',
       '2017-07-09T21:54:25.000000000', '2017-07-09T21:54:30.000000000',
       '2017-07-09T21:54:35.000000000', '2017-07-09T21:54:40.000000000',
       '2017-07-09T21:54:45.000000000', '2017-07-09T21:54:50.000000000',
       '2017-07-09T21:54:55.000000000', '2017-07-09T21:55:00.000000000',
       '2017-07-09T21:55:05.000000000', '2017-07-09T21:55:10.000000000',
       '2017-07-09T21:55:15.000000000', '2017-07-09T21:55:20.000000000',
       '2017-07-09T21:55:25.000000000', '2017-07-09T21:55:30.000000000',
       '2017-07-09T21:55:35.000000000', '2017-07-09T21:55:40.000000000',
       '2017-07-09T21:55:45.000000000', '2017-07-09T21:55:50.000000000',
       '2017-07-09T21:55:55.000000000', '2017-07-09T21:56:00.000000000',
       '2017-07-09T21:56:05.000000000', '2017-07-09T21:56:10.000000000',
       '2017-07-09T21:56:15.000000000', '2017-07-09T21:56:20.000000000',
       '2017-07-09T21:56:25.000000000', '2017-07-09T21:56:30.000000000',
       '2017-07-09T21:56:35.000000000', '2017-07-09T21:56:40.000000000',
       '2017-07-09T21:56:45.000000000', '2017-07-09T21:56:50.000000000',
       '2017-07-09T21:56:55.000000000', '2017-07-09T21:57:00.000000000',
       '2017-07-09T21:57:05.000000000', '2017-07-09T21:57:10.000000000',
       '2017-07-09T21:57:15.000000000', '2017-07-09T21:57:20.000000000',
       '2017-07-09T21:57:25.000000000', '2017-07-09T21:57:30.000000000',
       '2017-07-09T21:57:35.000000000', '2017-07-09T21:57:40.000000000',
       '2017-07-09T21:57:45.000000000', '2017-07-09T21:57:50.000000000',
       '2017-07-09T21:57:55.000000000', '2017-07-09T21:58:00.000000000',
       '2017-07-09T21:58:05.000000000', '2017-07-09T21:58:10.000000000',
       '2017-07-09T21:58:15.000000000', '2017-07-09T21:58:20.000000000',
       '2017-07-09T21:58:25.000000000', '2017-07-09T21:58:30.000000000',
       '2017-07-09T21:58:35.000000000', '2017-07-09T21:58:40.000000000',
       '2017-07-09T21:58:45.000000000', '2017-07-09T21:58:50.000000000',
       '2017-07-09T21:58:55.000000000', '2017-07-09T21:59:00.000000000',
       '2017-07-09T21:59:05.000000000', '2017-07-09T21:59:10.000000000',
       '2017-07-09T21:59:15.000000000', '2017-07-09T21:59:20.000000000',
       '2017-07-09T21:59:25.000000000', '2017-07-09T21:59:30.000000000',
       '2017-07-09T21:59:35.000000000', '2017-07-09T21:59:40.000000000',
       '2017-07-09T21:59:45.000000000', '2017-07-09T21:59:50.000000000',
       '2017-07-09T21:59:55.000000000', '2017-07-09T22:00:00.000000000',
       '2017-07-09T22:00:05.000000000', '2017-07-09T22:00:10.000000000',
       '2017-07-09T22:00:15.000000000', '2017-07-09T22:00:20.000000000',
       '2017-07-09T22:00:25.000000000', '2017-07-09T22:00:30.000000000',
       '2017-07-09T22:00:35.000000000', '2017-07-09T22:00:40.000000000',
       '2017-07-09T22:00:45.000000000', '2017-07-09T22:00:50.000000000',
       '2017-07-09T22:00:55.000000000', '2017-07-09T22:01:00.000000000',
       '2017-07-09T22:01:05.000000000', '2017-07-09T22:01:10.000000000',
       '2017-07-09T22:01:15.000000000', '2017-07-09T22:01:20.000000000',
       '2017-07-09T22:01:25.000000000', '2017-07-09T22:01:30.000000000',
       '2017-07-09T22:01:35.000000000', '2017-07-09T22:01:40.000000000',
       '2017-07-09T22:01:45.000000000', '2017-07-09T22:01:50.000000000',
       '2017-07-09T22:01:55.000000000', '2017-07-09T22:02:00.000000000',
       '2017-07-09T22:02:05.000000000', '2017-07-09T22:02:10.000000000',
       '2017-07-09T22:02:15.000000000', '2017-07-09T22:02:20.000000000',
       '2017-07-09T22:02:25.000000000', '2017-07-09T22:02:30.000000000',
       '2017-07-09T22:02:35.000000000', '2017-07-09T22:02:40.000000000',
       '2017-07-09T22:02:45.000000000', '2017-07-09T22:02:50.000000000',
       '2017-07-09T22:02:55.000000000', '2017-07-09T22:03:00.000000000',
       '2017-07-09T22:03:05.000000000', '2017-07-09T22:03:10.000000000',
       '2017-07-09T22:03:15.000000000', '2017-07-09T22:03:20.000000000',
       '2017-07-09T22:03:25.000000000', '2017-07-09T22:03:30.000000000',
       '2017-07-09T22:03:35.000000000', '2017-07-09T22:03:40.000000000',
       '2017-07-09T22:03:45.000000000', '2017-07-09T22:03:50.000000000',
       '2017-07-09T22:03:55.000000000', '2017-07-09T22:04:00.000000000',
       '2017-07-09T22:04:05.000000000', '2017-07-09T22:04:10.000000000',
       '2017-07-09T22:04:15.000000000', '2017-07-09T22:04:20.000000000',
       '2017-07-09T22:04:25.000000000', '2017-07-09T22:04:30.000000000',
       '2017-07-09T22:04:35.000000000', '2017-07-09T22:04:40.000000000',
       '2017-07-09T22:04:45.000000000', '2017-07-09T22:04:50.000000000',
       '2017-07-09T22:04:55.000000000', '2017-07-09T22:05:00.000000000',
       '2017-07-09T22:05:05.000000000', '2017-07-09T22:05:10.000000000',
       '2017-07-09T22:05:15.000000000', '2017-07-09T22:05:20.000000000',
       '2017-07-09T22:05:25.000000000', '2017-07-09T22:05:30.000000000',
       '2017-07-09T22:05:35.000000000', '2017-07-09T22:05:40.000000000',
       '2017-07-09T22:05:45.000000000', '2017-07-09T22:05:50.000000000',
       '2017-07-09T22:05:55.000000000', '2017-07-09T22:06:00.000000000',
       '2017-07-09T22:06:05.000000000', '2017-07-09T22:06:10.000000000',
       '2017-07-09T22:06:15.000000000', '2017-07-09T22:06:20.000000000',
       '2017-07-09T22:06:25.000000000', '2017-07-09T22:06:30.000000000',
       '2017-07-09T22:06:35.000000000', '2017-07-09T22:06:40.000000000',
       '2017-07-09T22:06:45.000000000', '2017-07-09T22:06:50.000000000',
       '2017-07-09T22:06:55.000000000', '2017-07-09T22:07:00.000000000',
       '2017-07-09T22:07:05.000000000', '2017-07-09T22:07:10.000000000',
       '2017-07-09T22:07:15.000000000', '2017-07-09T22:07:20.000000000',
       '2017-07-09T22:07:25.000000000', '2017-07-09T22:07:30.000000000',
       '2017-07-09T22:07:35.000000000', '2017-07-09T22:07:40.000000000',
       '2017-07-09T22:07:45.000000000', '2017-07-09T22:07:50.000000000',
       '2017-07-09T22:07:55.000000000', '2017-07-09T22:08:00.000000000',
       '2017-07-09T22:08:05.000000000', '2017-07-09T22:08:10.000000000',
       '2017-07-09T22:08:15.000000000', '2017-07-09T22:08:20.000000000',
       '2017-07-09T22:08:25.000000000', '2017-07-09T22:08:30.000000000',
       '2017-07-09T22:08:35.000000000', '2017-07-09T22:08:40.000000000',
       '2017-07-09T22:08:45.000000000', '2017-07-09T22:08:50.000000000',
       '2017-07-09T22:08:55.000000000', '2017-07-09T22:09:00.000000000',
       '2017-07-09T22:09:05.000000000', '2017-07-09T22:09:10.000000000',
       '2017-07-09T22:09:15.000000000', '2017-07-09T22:09:20.000000000',
       '2017-07-09T22:09:25.000000000', '2017-07-09T22:09:30.000000000',
       '2017-07-09T22:09:35.000000000', '2017-07-09T22:09:40.000000000',
       '2017-07-09T22:09:45.000000000', '2017-07-09T22:09:50.000000000',
       '2017-07-09T22:09:55.000000000', '2017-07-09T22:10:00.000000000',
       '2017-07-09T22:10:05.000000000', '2017-07-09T22:10:10.000000000',
       '2017-07-09T22:10:15.000000000', '2017-07-09T22:10:20.000000000',
       '2017-07-09T22:10:25.000000000', '2017-07-09T22:10:30.000000000',
       '2017-07-09T22:10:35.000000000', '2017-07-09T22:10:40.000000000',
       '2017-07-09T22:10:45.000000000', '2017-07-09T22:10:50.000000000',
       '2017-07-09T22:10:55.000000000', '2017-07-09T22:11:00.000000000',
       '2017-07-09T22:11:05.000000000', '2017-07-09T22:11:10.000000000',
       '2017-07-09T22:11:15.000000000', '2017-07-09T22:11:20.000000000',
       '2017-07-09T22:11:25.000000000', '2017-07-09T22:11:30.000000000',
       '2017-07-09T22:11:35.000000000', '2017-07-09T22:11:40.000000000',
       '2017-07-09T22:11:45.000000000', '2017-07-09T22:11:50.000000000',
       '2017-07-09T22:11:55.000000000', '2017-07-09T22:12:00.000000000',
       '2017-07-09T22:12:05.000000000', '2017-07-09T22:12:10.000000000',
       '2017-07-09T22:12:15.000000000', '2017-07-09T22:12:20.000000000',
       '2017-07-09T22:12:25.000000000', '2017-07-09T22:12:30.000000000',
       '2017-07-09T22:12:35.000000000', '2017-07-09T22:12:40.000000000',
       '2017-07-09T22:12:45.000000000', '2017-07-09T22:12:50.000000000',
       '2017-07-09T22:12:55.000000000', '2017-07-09T22:13:00.000000000',
       '2017-07-09T22:13:05.000000000', '2017-07-09T22:13:10.000000000',
       '2017-07-09T22:13:15.000000000', '2017-07-09T22:13:20.000000000',
       '2017-07-09T22:13:25.000000000', '2017-07-09T22:13:30.000000000',
       '2017-07-09T22:13:35.000000000', '2017-07-09T22:13:40.000000000',
       '2017-07-09T22:13:45.000000000', '2017-07-09T22:13:50.000000000',
       '2017-07-09T22:13:55.000000000', '2017-07-09T22:14:00.000000000',
       '2017-07-09T22:14:05.000000000', '2017-07-09T22:14:10.000000000',
       '2017-07-09T22:14:15.000000000', '2017-07-09T22:14:20.000000000',
       '2017-07-09T22:14:25.000000000', '2017-07-09T22:14:30.000000000',
       '2017-07-09T22:14:35.000000000', '2017-07-09T22:14:40.000000000',
       '2017-07-09T22:14:45.000000000', '2017-07-09T22:14:50.000000000',
       '2017-07-09T22:14:55.000000000', '2017-07-09T22:15:00.000000000',
       '2017-07-09T22:15:05.000000000', '2017-07-09T22:15:10.000000000',
       '2017-07-09T22:15:15.000000000', '2017-07-09T22:15:20.000000000',
       '2017-07-09T22:15:25.000000000', '2017-07-09T22:15:30.000000000',
       '2017-07-09T22:15:35.000000000', '2017-07-09T22:15:40.000000000',
       '2017-07-09T22:15:45.000000000', '2017-07-09T22:15:50.000000000',
       '2017-07-09T22:15:55.000000000', '2017-07-09T22:16:00.000000000',
       '2017-07-09T22:16:05.000000000', '2017-07-09T22:16:10.000000000',
       '2017-07-09T22:16:15.000000000', '2017-07-09T22:16:20.000000000',
       '2017-07-09T22:16:25.000000000', '2017-07-09T22:16:30.000000000',
       '2017-07-09T22:16:35.000000000', '2017-07-09T22:16:40.000000000',
       '2017-07-09T22:16:45.000000000', '2017-07-09T22:16:50.000000000',
       '2017-07-09T22:16:55.000000000', '2017-07-09T22:17:00.000000000',
       '2017-07-09T22:17:05.000000000', '2017-07-09T22:17:10.000000000',
       '2017-07-09T22:17:15.000000000', '2017-07-09T22:17:20.000000000',
       '2017-07-09T22:17:25.000000000', '2017-07-09T22:17:30.000000000',
       '2017-07-09T22:17:35.000000000', '2017-07-09T22:17:40.000000000',
       '2017-07-09T22:17:45.000000000', '2017-07-09T22:17:50.000000000',
       '2017-07-09T22:17:55.000000000', '2017-07-09T22:18:00.000000000',
       '2017-07-09T22:18:05.000000000', '2017-07-09T22:18:10.000000000',
       '2017-07-09T22:18:15.000000000', '2017-07-09T22:18:20.000000000',
       '2017-07-09T22:18:25.000000000', '2017-07-09T22:18:30.000000000',
       '2017-07-09T22:18:35.000000000', '2017-07-09T22:18:40.000000000',
       '2017-07-09T22:18:45.000000000', '2017-07-09T22:18:50.000000000',
       '2017-07-09T22:18:55.000000000', '2017-07-09T22:19:00.000000000',
       '2017-07-09T22:19:05.000000000', '2017-07-09T22:19:10.000000000',
       '2017-07-09T22:19:15.000000000', '2017-07-09T22:19:20.000000000',
       '2017-07-09T22:19:25.000000000', '2017-07-09T22:19:30.000000000',
       '2017-07-09T22:19:35.000000000', '2017-07-09T22:19:40.000000000',
       '2017-07-09T22:19:45.000000000', '2017-07-09T22:19:50.000000000',
       '2017-07-09T22:19:55.000000000', '2017-07-09T22:20:00.000000000',
       '2017-07-09T22:20:05.000000000', '2017-07-09T22:20:10.000000000',
       '2017-07-09T22:20:15.000000000', '2017-07-09T22:20:20.000000000',
       '2017-07-09T22:20:25.000000000', '2017-07-09T22:20:30.000000000',
       '2017-07-09T22:20:35.000000000', '2017-07-09T22:20:40.000000000',
       '2017-07-09T22:20:45.000000000', '2017-07-09T22:20:50.000000000',
       '2017-07-09T22:20:55.000000000', '2017-07-09T22:21:00.000000000',
       '2017-07-09T22:21:05.000000000', '2017-07-09T22:21:10.000000000',
       '2017-07-09T22:21:15.000000000', '2017-07-09T22:21:20.000000000',
       '2017-07-09T22:21:25.000000000', '2017-07-09T22:21:30.000000000',
       '2017-07-09T22:21:35.000000000', '2017-07-09T22:21:40.000000000',
       '2017-07-09T22:21:45.000000000', '2017-07-09T22:21:50.000000000',
       '2017-07-09T22:21:55.000000000', '2017-07-09T22:22:00.000000000',
       '2017-07-09T22:22:05.000000000', '2017-07-09T22:22:10.000000000',
       '2017-07-09T22:22:15.000000000', '2017-07-09T22:22:20.000000000',
       '2017-07-09T22:22:25.000000000', '2017-07-09T22:22:30.000000000',
       '2017-07-09T22:22:35.000000000', '2017-07-09T22:22:40.000000000',
       '2017-07-09T22:22:45.000000000', '2017-07-09T22:22:50.000000000',
       '2017-07-09T22:22:55.000000000', '2017-07-09T22:23:00.000000000',
       '2017-07-09T22:23:05.000000000', '2017-07-09T22:23:10.000000000',
       '2017-07-09T22:23:15.000000000', '2017-07-09T22:23:20.000000000',
       '2017-07-09T22:23:25.000000000', '2017-07-09T22:23:30.000000000',
       '2017-07-09T22:23:35.000000000', '2017-07-09T22:23:40.000000000',
       '2017-07-09T22:23:45.000000000', '2017-07-09T22:23:50.000000000',
       '2017-07-09T22:23:55.000000000', '2017-07-09T22:24:00.000000000',
       '2017-07-09T22:24:05.000000000', '2017-07-09T22:24:10.000000000',
       '2017-07-09T22:24:15.000000000', '2017-07-09T22:24:20.000000000',
       '2017-07-09T22:24:25.000000000', '2017-07-09T22:24:30.000000000',
       '2017-07-09T22:24:35.000000000', '2017-07-09T22:24:40.000000000',
       '2017-07-09T22:24:45.000000000', '2017-07-09T22:24:50.000000000',
       '2017-07-09T22:24:55.000000000', '2017-07-09T22:25:00.000000000',
       '2017-07-09T22:25:05.000000000', '2017-07-09T22:25:10.000000000',
       '2017-07-09T22:25:15.000000000', '2017-07-09T22:25:20.000000000',
       '2017-07-09T22:25:25.000000000', '2017-07-09T22:25:30.000000000',
       '2017-07-09T22:25:35.000000000', '2017-07-09T22:25:40.000000000',
       '2017-07-09T22:25:45.000000000', '2017-07-09T22:25:50.000000000',
       '2017-07-09T22:25:55.000000000', '2017-07-09T22:26:00.000000000',
       '2017-07-09T22:26:05.000000000', '2017-07-09T22:26:10.000000000',
       '2017-07-09T22:26:15.000000000', '2017-07-09T22:26:20.000000000',
       '2017-07-09T22:26:25.000000000', '2017-07-09T22:26:30.000000000',
       '2017-07-09T22:26:35.000000000', '2017-07-09T22:26:40.000000000',
       '2017-07-09T22:26:45.000000000', '2017-07-09T22:26:50.000000000',
       '2017-07-09T22:26:55.000000000', '2017-07-09T22:27:00.000000000',
       '2017-07-09T22:27:05.000000000', '2017-07-09T22:27:10.000000000',
       '2017-07-09T22:27:15.000000000', '2017-07-09T22:27:20.000000000',
       '2017-07-09T22:27:25.000000000', '2017-07-09T22:27:30.000000000',
       '2017-07-09T22:27:35.000000000', '2017-07-09T22:27:40.000000000',
       '2017-07-09T22:27:45.000000000', '2017-07-09T22:27:50.000000000',
       '2017-07-09T22:27:55.000000000', '2017-07-09T22:28:00.000000000',
       '2017-07-09T22:28:05.000000000', '2017-07-09T22:28:10.000000000',
       '2017-07-09T22:28:15.000000000', '2017-07-09T22:28:20.000000000',
       '2017-07-09T22:28:25.000000000', '2017-07-09T22:28:30.000000000',
       '2017-07-09T22:28:35.000000000', '2017-07-09T22:28:40.000000000',
       '2017-07-09T22:28:45.000000000', '2017-07-09T22:28:50.000000000',
       '2017-07-09T22:28:55.000000000', '2017-07-09T22:29:00.000000000',
       '2017-07-09T22:29:05.000000000', '2017-07-09T22:29:10.000000000',
       '2017-07-09T22:29:15.000000000', '2017-07-09T22:29:20.000000000',
       '2017-07-09T22:29:25.000000000', '2017-07-09T22:29:30.000000000',
       '2017-07-09T22:29:35.000000000', '2017-07-09T22:29:40.000000000',
       '2017-07-09T22:29:45.000000000', '2017-07-09T22:29:50.000000000',
       '2017-07-09T22:29:55.000000000', '2017-07-09T22:30:00.000000000',
       '2017-07-09T22:30:05.000000000', '2017-07-09T22:30:10.000000000',
       '2017-07-09T22:30:15.000000000', '2017-07-09T22:30:20.000000000',
       '2017-07-09T22:30:25.000000000', '2017-07-09T22:30:30.000000000',
       '2017-07-09T22:30:35.000000000', '2017-07-09T22:30:40.000000000',
       '2017-07-09T22:30:45.000000000', '2017-07-09T22:30:50.000000000',
       '2017-07-09T22:30:55.000000000', '2017-07-09T22:31:00.000000000',
       '2017-07-09T22:31:05.000000000', '2017-07-09T22:31:10.000000000',
       '2017-07-09T22:31:15.000000000', '2017-07-09T22:31:20.000000000',
       '2017-07-09T22:31:25.000000000', '2017-07-09T22:31:30.000000000',
       '2017-07-09T22:31:35.000000000', '2017-07-09T22:31:40.000000000',
       '2017-07-09T22:31:45.000000000', '2017-07-09T22:31:50.000000000',
       '2017-07-09T22:31:55.000000000', '2017-07-09T22:32:00.000000000',
       '2017-07-09T22:32:05.000000000', '2017-07-09T22:32:10.000000000',
       '2017-07-09T22:32:15.000000000', '2017-07-09T22:32:20.000000000',
       '2017-07-09T22:32:25.000000000', '2017-07-09T22:32:30.000000000',
       '2017-07-09T22:32:35.000000000', '2017-07-09T22:32:40.000000000',
       '2017-07-09T22:32:45.000000000', '2017-07-09T22:32:50.000000000',
       '2017-07-09T22:32:55.000000000', '2017-07-09T22:33:00.000000000',
       '2017-07-09T22:33:05.000000000', '2017-07-09T22:33:10.000000000',
       '2017-07-09T22:33:15.000000000', '2017-07-09T22:33:20.000000000',
       '2017-07-09T22:33:25.000000000', '2017-07-09T22:33:30.000000000',
       '2017-07-09T22:33:35.000000000', '2017-07-09T22:33:40.000000000',
       '2017-07-09T22:33:45.000000000', '2017-07-09T22:33:50.000000000',

In [19]:
ds_norm['ping_time'].attrs

{'axis': 'T', 'long_name': 'Ping time', 'standard_name': 'time'}